[2024-05-20T04:46:29.415+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T04:46:29.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.primera_tarea manual__2024-05-20T04:30:08.190448+00:00 [queued]>
[2024-05-20T04:46:29.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.primera_tarea manual__2024-05-20T04:30:08.190448+00:00 [queued]>
[2024-05-20T04:46:29.440+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-20T04:46:29.451+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): primera_tarea> on 2024-05-20 04:30:08.190448+00:00
[2024-05-20T04:46:29.456+0000] {standard_task_runner.py:63} INFO - Started process 294 to run task
[2024-05-20T04:46:29.458+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'primera_tarea', 'manual__2024-05-20T04:30:08.190448+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpv0qbioye']
[2024-05-20T04:46:29.459+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask primera_tarea
[2024-05-20T04:46:29.489+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.primera_tarea manual__2024-05-20T04:30:08.190448+00:00 [running]> on host 8251e45c28eb
[2024-05-20T04:46:29.549+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='primera_tarea' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T04:30:08.190448+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T04:30:08.190448+00:00'
[2024-05-20T04:46:29.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T04:46:29.558+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-20T04:46:29.558+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Iniciando...']
[2024-05-20T04:46:29.567+0000] {subprocess.py:86} INFO - Output:
[2024-05-20T04:46:29.569+0000] {subprocess.py:93} INFO - Iniciando...
[2024-05-20T04:46:29.570+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-20T04:46:29.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T04:46:29.589+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_ETL, task_id=primera_tarea, run_id=manual__2024-05-20T04:30:08.190448+00:00, execution_date=20240520T043008, start_date=20240520T044629, end_date=20240520T044629
[2024-05-20T04:46:29.630+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T04:46:29.650+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-20T04:46:29.651+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
