[2024-05-20T04:46:29.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T04:46:29.976+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:30:08.190448+00:00 [queued]>
[2024-05-20T04:46:29.983+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:30:08.190448+00:00 [queued]>
[2024-05-20T04:46:29.983+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-20T04:46:29.994+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 04:30:08.190448+00:00
[2024-05-20T04:46:29.999+0000] {standard_task_runner.py:63} INFO - Started process 297 to run task
[2024-05-20T04:46:30.001+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'manual__2024-05-20T04:30:08.190448+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjrva66mt']
[2024-05-20T04:46:30.002+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask transformar_data
[2024-05-20T04:46:30.034+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:30:08.190448+00:00 [running]> on host 8251e45c28eb
[2024-05-20T04:46:30.095+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T04:30:08.190448+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T04:30:08.190448+00:00'
[2024-05-20T04:46:30.096+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T04:46:30.760+0000] {logging_mixin.py:188} INFO - {'Error Message': 'Invalid API KEY. Feel free to create a Free API Key or visit https://site.financialmodelingprep.com/faqs?search=why-is-my-api-key-invalid for more information.'}
[2024-05-20T04:46:30.762+0000] {python.py:237} INFO - Done. Returned value was: {'Error Message': 'Invalid API KEY. Feel free to create a Free API Key or visit https://site.financialmodelingprep.com/faqs?search=why-is-my-api-key-invalid for more information.'}
[2024-05-20T04:46:30.762+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T04:46:30.778+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_ETL, task_id=transformar_data, run_id=manual__2024-05-20T04:30:08.190448+00:00, execution_date=20240520T043008, start_date=20240520T044629, end_date=20240520T044630
[2024-05-20T04:46:30.814+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T04:46:30.834+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-20T04:46:30.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
